### ISSUE TITLE
tests/main.py test fails to compile

### ISSUE THREAD

**Issue by pfvogel** [kisvegabor/lvgl#7299]
### LVGL version

latest 9.2.2

### What happened?

Copied lv_conf_template.h to lv_conf.h and changed #if 0 to #if 1
 
./tests/main.py --clean build
./tests/main.py test

Fails to compile with the following error message

```
====================================================================
Building: test_sysheap: Test config, system heap, 32 bit color depth
====================================================================

[20/388] Linking CXX executable test_draw_sw_post_process
FAILED: test_draw_sw_post_process 
: && /usr/bin/c++ -g  CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o CMakeFiles/test_draw_sw_post_process.dir/test_draw_sw_post_process_Runner.c.o CMakeFiles/test_draw_sw_post_process.dir/wayland_protocols/wayland_xdg_shell.c.o -o test_draw_sw_post_process  -lwayland-client  -lwayland-cursor  -lxkbcommon  libtest_common.a  lib/liblvgl_demos.a  lib/liblvgl.a  lib/liblvgl_thorvg.a  /usr/lib/x86_64-linux-gnu/libpng.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libfreetype.so  /usr/lib/x86_64-linux-gnu/libjpeg.so  -lm  -lpthread  -fsanitize=address  -fsanitize=leak  -fsanitize=undefined  --coverage  libtest_libs.a  lib/liblvgl.a  -lwayland-client  -lwayland-cursor  -lxkbcommon && :
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_rotate90_RGB565':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:31: undefined reference to `lv_draw_sw_rotate'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_rotate180_RGB565':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:52: undefined reference to `lv_draw_sw_rotate'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_rotate270_RGB565':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:76: undefined reference to `lv_draw_sw_rotate'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_rotate90_RGB888':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:100: undefined reference to `lv_draw_sw_rotate'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_rotate180_RGB888':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:123: undefined reference to `lv_draw_sw_rotate'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o:/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:147: more undefined references to `lv_draw_sw_rotate' follow
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_invert':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:304: undefined reference to `lv_draw_sw_i1_invert'
/usr/bin/ld: /home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:309: undefined reference to `lv_draw_sw_i1_invert'
/usr/bin/ld: /home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:314: undefined reference to `lv_draw_sw_i1_invert'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_vtile_small':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:326: undefined reference to `lv_draw_sw_i1_convert_to_vtiled'
/usr/bin/ld: /home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:329: undefined reference to `lv_draw_sw_i1_convert_to_vtiled'
/usr/bin/ld: CMakeFiles/test_draw_sw_post_process.dir/src/test_cases/draw/test_draw_sw_post_process.c.o: in function `test_vtile_rectangular':
/home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:440: undefined reference to `lv_draw_sw_i1_convert_to_vtiled'
/usr/bin/ld: /home/paul/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c:443: undefined reference to `lv_draw_sw_i1_convert_to_vtiled'
collect2: error: ld returned 1 exit status
[23/388] Building C object CMakeFiles/...rm.dir/test_layer_transform_Runner.c.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/paul/lvgl/./tests/main.py", line 259, in <module>
    build_tests(options_name, build_type, args.clean)
  File "/home/paul/lvgl/./tests/main.py", line 138, in build_tests
    subprocess.check_call(['cmake', '--build', build_dir,
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/paul/lvgl/tests/build_test_sysheap', '--parallel', '4']' returned non-zero exit status 1.
```

### How to reproduce?

git bisect shows 

```
7bccca027a5fe651de03b2037f2857fa3d53f846 is the first bad commit
commit 7bccca027a5fe651de03b2037f2857fa3d53f846
Author: Gabor Kiss-Vamosi <kisvegabor@gmail.com>
Date:   Wed Nov 13 12:37:37 2024 +0100

    chore(api): prevent API leaks (cache and thread) (#7220)

```
as the first failing commit

**Comment by pfvogel** [comment]
Commenting out this line in the tests/CMakeLists.txt file allows the compilation of the test and the tests to run

```
 elseif (OPTIONS_TEST_SYSHEAP)
     set (BUILD_OPTIONS ${LVGL_TEST_OPTIONS_TEST_SYSHEAP})
     filter_compiler_options (C TEST_LIBS ${SANITIZE_AND_COVERAGE_OPTIONS})
-    set (LV_CONF_BUILD_DISABLE_EXAMPLES ON)
+#    set (LV_CONF_BUILD_DISABLE_EXAMPLES ON)
     set (ENABLE_TESTS ON)
```
This doesn't seem like the correct fix though.  It may just be making it work because one of the examples is causing the lv_draw_sw_utils.c to be included in the build and allowing the test to link.

**Comment by pfvogel** [comment]
This no longer fails in the current version.
