### ISSUE TITLE
no member named 'clip_area'?

### ISSUE THREAD

**Issue by cuishuang413** [kisvegabor/lvgl#3936]
Hello,

I have been trying to compile the live widgt demo, but I got this error and don't know where to start. Please help!

error: 'lv_obj_draw_part_dsc_t' {aka 'struct <anonymous>'} has no member named 'clip_area'; did you mean 'draw_area'?

Thanks,

**Comment by kisvegabor** [comment]
Do you use the `release/v8.3` branch? If not, please use it as `master` is under development and it might be unstable.

**Comment by cuishuang413** [comment]
That fixed it. Thanks!

**Comment by wolfgangwayland7** [comment]
For your information the "lvgl-release-v8.3" {down load as a zip only or cloned} still dose not have 
"clip_area" defined inside the {lv_obj_draw_part_dsc_t  [struct]}     of the  as of  2-11-2023

The struct is int the "lv_obj_draw.h" header inside the "lvgl-release-v8.3/src/core" folder...

I don't know which which file  user "cuishuang413" downloaded? I'd like to know.. Thanks

**Comment by kisvegabor** [comment]
@wolfgangwayland7 Exactly what is not working? We have CI running on each commit testing the demos so they should work on the release/v8.3 branch.

**Comment by kisvegabor** [comment]
Let's continue in #3982
