### ISSUE TITLE
ThorVG: Compilation failure on thread-less targets

### ISSUE THREAD

**Issue by technophil98** [kisvegabor/lvgl#8362]
### LVGL version

9.3.0

### Platform

STM32H7 with ARM GNU Toolchain arm-none-eabi 13.2 using nano.specs (_newlib-nano_)

### What happened?

`using` statements in [tvgTaskScheduler.h](https://github.com/lvgl/lvgl/blob/c033a98afddd65aaafeebea625382a94020fe4a7/src/libs/thorvg/tvgTaskScheduler.h#L36) results in the following compiler error:

```
lvgl/src/libs/thorvg/tvgTaskScheduler.h:36:12: error: 'mutex' has not been declared in 'std'
   36 | using std::mutex;
      |            ^~~~~
lvgl/src/libs/thorvg/tvgTaskScheduler.h:37:12: error: 'condition_variable' has not been declared in 'std'
   37 | using std::condition_variable;
      |            ^~~~~~~~~~~~~~~~~~
```

`std::mutex` and `std::condition_variable` are usually not available/not applicable on MCU targets.

Concerned changes introduced in #8043
