### ISSUE TITLE
Wrong function return result

### ISSUE THREAD

**Issue by Barto22** [kisvegabor/lvgl#3265]
### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
On master branch and tag v8.2 in file lv_event.c in function void * lv_obj_get_event_user_data(struct _lv_obj_t * obj, lv_event_cb_t event_cb) in line 257 if obj->spec_attr == NULL function return false instead of NULL and I get compiler error on arm-none-eabi-gcc version 10.3.1.

### To Reproduce
Compile with arm-none-eabi-gcc 10.3.1.
Compiler error: incompatible types when returning type '_Bool' but 'void *' was expected 

### Expected behavior
No compiler errors.

**Comment by embeddedt** [comment]
Thanks for noting this! I'm not sure why there is no warning on CI (or locally, for that matter) when returning a boolean without casting. I'll need to look into this further.

**Comment by embeddedt** [comment]
Upon doing some further research, it appears that the lack of a CI error is caused by the fact that many compilers allow implicit conversion of the integral value `0` to a pointer without a warning, e.g.:

```c
void *test_fn(void)
{
    return 0;
}
```

There doesn't seem to be a way to force the compiler to error in this specific scenario, and `false` will be equal to NULL on practically every platform, so I don't think it's an edge case worth being concerned about.

Returning `true` in that situation would cause an error as expected.
