### PR TITLE
In lv_linux_fbdev, no lvgl.h header file issue fixed

### PR DESCRIPTION
**Pull request by rmshub**
### Description of the feature or fix

lvgl/lvgl.h: No such file or directory compilation error observed when LV_LVGL_H_INCLUDE_SIMPLE defined.

### Checkpoints
- Verified code by build for Cortex-A7 processor with GCC complier

### CODE REVIEW

**Review by C47D — APPROVED** [review]
Looks good to me, fixes #5191 

CI failure not related to change, reported in #5182

File: src/dev/display/fb/lv_linux_fbdev.c [hunk 1]
```diff
@@ -26,7 +26,11 @@
     #include <linux/fb.h>
 #endif /* LV_LINUX_FBDEV_BSD */
 
-#include <lvgl/lvgl.h>
+#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
```
Comment (kisvegabor) [inline src/dev/display/fb/lv_linux_fbdev.c]: We should use a relative include, similar to [this](https://github.com/lvgl/lvgl/blob/master/src/dev/x11/lv_x11.h#L17).

**Review by kisvegabor — CHANGES_REQUESTED** [review]

File: src/dev/display/fb/lv_linux_fbdev.c (hunk 1 above)
Comment (rmshub) [reply src/dev/display/fb/lv_linux_fbdev.c]: The <lvgl/lvgl.h> inclusion is not required for drivers

**Comment by kisvegabor** [comment]
It's even better :slightly_smiling_face: Thanks!

**Review by kisvegabor — APPROVED** [review]
