### PR TITLE
fix(ci) Remove VARIANT on Micropython CI

### PR DESCRIPTION
**Pull request by amirgon**
After updating the Micropython bindings to v1.20, need a small fix to the Micropython CI in LVGL

### CODE REVIEW

**Comment by amirgon** [comment]
I'm actually not sure why the RP2 port fails...   
A very similar workflow passes: https://github.com/lvgl/lv_micropython/actions/runs/5305529952/jobs/9602554210

The error is
```
   micropython-lib not initialized.
   Run 'make BOARD=PICO submodules'
```

Although submodules are updated with:
```
make -C ports/rp2 BOARD=PICO USER_C_MODULES=../../lib/lv_bindings/bindings.cmake submodules
```

**Comment by kisvegabor** [comment]
Is it working locally?

**Comment by amirgon** [comment]
@kisvegabor It's fixed, but I think that some LVGL commit already broke Micropython.
That shows how important it is to keep the micropython CI functional.

```
../../lib/lv_bindings/lvgl/src/misc/lv_anim.c: In function ‘lv_anim_path_ease_in’:
Error: ../../lib/lv_bindings/lvgl/src/misc/lv_anim.c:28:81: error: conversion from ‘double’ to ‘int32_t’ {aka ‘int’} changes value from ‘4.3007999999999998e+2’ to ‘430’ [-Werror=float-conversion]
   28 | #define _path_cubic_bezier(a, x1, x2, y1, y2) lv_anim_path_cubic_bezier(a, (x1) * 1024, (y1) * 1024, (x2) * 1024, (y2) * 1024)
      |                                                                            ~~~~~^~~~~~
../../lib/lv_bindings/lvgl/src/misc/lv_anim.c:228:12: note: in expansion of macro ‘_path_cubic_bezier’
  228 |     return _path_cubic_bezier(a, 0.42, 0.0, 1.0, 1.0);
      |            ^~~~~~~~~~~~~~~~~~
```

**Comment by kisvegabor** [comment]
> That shows how important it is to keep the micropython CI functional.

:+1: 

@XuNeo could you take a look at this?

**Comment by kisvegabor** [comment]
I merge it first, to see if the updates of @XuNeo could fix the problem.
