### ISSUE TITLE
LVGL froze after migrating from version 7 to 8.4

### ISSUE THREAD

**Issue by arilink** [kisvegabor/lvgl#8618]
### LVGL version

8.4

### Platform

semdriver D9360 cortex-R
RTOS:Free RTOS

### What happened?

My project previously used lvgl7. I attempted to upgrade to lvgl8. Currently, there are no compilation errors, but the app enters hardfault when running. I gradually located the issue to lv_timer_handler being stuck. I added print statements in lv_timer_handler and found that it got stuck at the position shown in the following figure. Could you please tell me what might be the problem causing the stuck?

<img width="885" height="499" alt="Image" src="https://github.com/user-attachments/assets/a9fed51c-08d7-4482-9b54-6056d4a54ca2" />

<img width="340" height="196" alt="Image" src="https://github.com/user-attachments/assets/508bf226-9ff1-4d5d-b9a1-9c37d563149c" />

**Comment by kisvegabor** [comment]
Once you are upgrading can you update to v9 instead? It'd be more future proof.

**Comment by arilink** [comment]
> Once you are upgrading can you update to v9 instead? It'd be more future proof.

Most of my projects have been developed using LVGL8, but I am also capable of attempting to port them to LVGL9 for verification.

**Comment by arilink** [comment]
I USE LVGL V9,there is same err, I save all log,can you help me to analysic this problem?

[trace1.txt](https://github.com/user-attachments/files/21589335/trace1.txt)

> Once you are upgrading can you update to v9 instead? It'd be more future proof.

**Comment by kisvegabor** [comment]
I can't see anything suspicious in the logs. How do you create and initialize the display?
Please take look at [this migration guide](https://docs.lvgl.io/9.0/CHANGELOG.html#migration-guide).
