### ISSUE TITLE
Arduino demo 

### ISSUE THREAD

**Issue by panzerrr** [kisvegabor/lvgl#2706]
Hi I was trying to get the demo running on my m5stack, I followed the instructions in the document but it never worked....
```
#include <lvgl.h>
#include <TFT_eSPI.h>
/*If you want to use the LVGL examples,
  make sure to install the lv_examples Arduino library
  and uncomment the following line.
#include <lv_examples.h>
*/
#include <lv_examples.h>
#include <lv_demo.h>

TFT_eSPI tft = TFT_eSPI(); /* TFT instance */

/*Change to your screen resolution*/
static const uint32_t screenWidth  = 320;
static const uint32_t screenHeight = 240;

static lv_disp_draw_buf_t draw_buf;
static lv_color_t buf[ screenWidth * 10 ];

#if LV_USE_LOG != 0
/* Serial debugging */
void my_print( lv_log_level_t level, const char * file, uint32_t line, const char * fn_name, const char * dsc )
{
   Serial.printf( "%s(%s)@%d->%s\r\n", file, fn_name, line, dsc );
   Serial.flush();
}
#endif

/* Display flushing */
void my_disp_flush( lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p )
{
   uint32_t w = ( area->x2 - area->x1 + 1 );
   uint32_t h = ( area->y2 - area->y1 + 1 );

   tft.startWrite();
   tft.setAddrWindow( area->x1, area->y1, w, h );
   tft.pushColors( ( uint16_t * )&color_p->full, w * h, true );
   tft.endWrite();

   lv_disp_flush_ready( disp );
}

/*Read the touchpad*/
void my_touchpad_read( lv_indev_drv_t * indev_driver, lv_indev_data_t * data )
{
   uint16_t touchX, touchY;

   bool touched = tft.getTouch( &touchX, &touchY, 600 );

   if( !touched )
   {
      data->state = LV_INDEV_STATE_REL;
   }
   else
   {
      data->state = LV_INDEV_STATE_PR;

      /*Set the coordinates*/
      data->point.x = touchX;
      data->point.y = touchY;

      Serial.print( "Data x " );
      Serial.println( touchX );

      Serial.print( "Data y " );
      Serial.println( touchY );
   }
}

void setup()
{
   Serial.begin( 115200 ); /* prepare for possible serial debug */
   Serial.println( "Hello Arduino! (V8.0.X)" );
   Serial.println( "I am LVGL_Arduino" );

   lv_init();

#if LV_USE_LOG != 0
   lv_log_register_print_cb( my_print ); /* register print function for debugging */
#endif

   tft.begin();          /* TFT init */
   tft.setRotation( 3 ); /* Landscape orientation, flipped */

   /*Set the touchscreen calibration data,
     the actual data for your display can be aquired using
     the Generic -> Touch_calibrate example from the TFT_eSPI library*/
   uint16_t calData[5] = { 275, 3620, 264, 3532, 1 };
   tft.setTouch( calData );

   lv_disp_draw_buf_init( &draw_buf, buf, NULL, screenWidth * 10 );

   /*Initialize the display*/
   static lv_disp_drv_t disp_drv;
   lv_disp_drv_init( &disp_drv );
   /*Change the following line to your display resolution*/
   disp_drv.hor_res = screenWidth;
   disp_drv.ver_res = screenHeight;
   disp_drv.flush_cb = my_disp_flush;
   disp_drv.draw_buf = &draw_buf;
   lv_disp_drv_register( &disp_drv );

   /*Initialize the (dummy) input device driver*/
   static lv_indev_drv_t indev_drv;
   lv_indev_drv_init( &indev_drv );
   indev_drv.type = LV_INDEV_TYPE_POINTER;
   indev_drv.read_cb = my_touchpad_read;
   lv_indev_drv_register( &indev_drv );

#if 0
   /* Create simple label */
   lv_obj_t *label = lv_label_create( lv_scr_act() );
   lv_label_set_text( label, "Hello Arduino! (V8.0.X)" );
   lv_obj_align( label, LV_ALIGN_CENTER, 0, 0 );
#else
   /* Try an example from the lv_examples Arduino library
      make sure to include it as written above.
   lv_example_btn_1();
   */

   // uncomment one of these demos
   lv_demo_widgets();            // OK
   // lv_demo_benchmark();          // OK
   // lv_demo_keypad_encoder();     // works, but I haven't an encoder
   // lv_demo_music();              // NOK
   // lv_demo_printer();
   // lv_demo_stress();             // seems to be OK
#endif
   Serial.println( "Setup done" );
}

void loop()
{   
   lv_timer_handler(); /* let the GUI do its work */
   lv_tick_inc(5);
   delay( 5 );
}
```
I've followed the instruction and saved lv_conf.h and lv_demo_conf.h in the arduino library folder but it seems it never read the headers, i noticed that in the instruction it was `lv_ex_conf.h` so was this a problem? I'm trying desperatly 

```

LVGL_Arduino:8:10: fatal error: lv_examples.h: No such file or directory
 #include <lv_examples.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
lv_examples.h: No such file or directory
```

**Comment by kisvegabor** [comment]
These instructions seems a little bit outdated. Where have you found them?

**Comment by panzerrr** [comment]
> These instructions seems a little bit outdated. Where have you found them?

Hi sir I was just reading the instruction on docs.lvgl.io. 

i'm really confused and now i commented the `#include<lv_examples.h>` and enable the widget demo the error turned to 
```
C:\Users\liabao\Documents\Arduino\libraries\lv_examples\src\lv_demo_widgets\assets\img_clothes.c:4:10: fatal error: lvgl/lvgl.h: No such file or directory
 #include "lvgl/lvgl.h"
          ^~~~~~~~~~~~~
compilation terminated.
exit status 1
```

**Comment by kisvegabor** [comment]
> Hi sir I was just reading the instruction on docs.lvgl.io.


Here https://docs.lvgl.io/master/get-started/arduino.html ?
It doesn't mention `#include<lv_examples.h>`.


> i'm really confused and now i commented the #include<lv_examples.h> and enable the widget demo the error turned to

I updated lv_demo.h 

Could you try again?

**Comment by panzerrr** [comment]
> > Hi sir I was just reading the instruction on docs.lvgl.io.
> 
> Here https://docs.lvgl.io/master/get-started/arduino.html ? It doesn't mention `#include<lv_examples.h>`.
> 
> > i'm really confused and now i commented the #include<lv_examples.h> and enable the widget demo the error turned to
> 
> I updated lv_demo.h
> 
> Could you try again?

Yes I read instruction for the lastest and 7.10.1 as well, and now I switched to the 8.0.1 version for both lv_example and lvgl library for arduino. I even tried my laptop, the same error prompted out. 

Basically I configured the TFT_eSPI library and switched the setup to M5stack, and then I enabled `lv_conf.h`, changed the colour depth and copied this file to my arduino library folder. After that I did the same thing for `lv_demo_conf.h` by enabling the  `LV_USE_DEMO_WIDGETS` and left everything else 0. 

For the last step I just changed the resolution in LVGL_Arduino and then everytime i when i compile it, the error prompt out 
```C:\Users\liabao\Documents\Arduino\libraries\lv_examples\src\lv_demo_widgets\assets\img_clothes.c:4:10:`` fatal error: lvgl/lvgl.h: No such file or directory
 #include "lvgl/lvgl.h"
          ^~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board M5Stack-Core2.```
if I uncomment `#include<lv_examples.h>`, it just says 
```
lv_examples.h: No such file or directory
```

I'm really confused and I also tried this on my laptop, I got exactly same error.

**Comment by panzerrr** [comment]
after i changed the lv_examples.h to absolute path my headers became
```
#include` <lvgl.h>
#include <TFT_eSPI.h>
/*If you want to use the LVGL examples,
  make sure to install the lv_examples Arduino library
  and uncomment the following line.
#include <lv_examples.h>
*/
#include "C:\Users\liabao\Documents\Arduino\libraries\lvgl\examples\lv_examples.h"
#include <lv_demo.h>
 ```
while new errors regarding the header prompted up 
```
 C:\Users\liabao\Documents\Arduino\libraries\lv_examples\src\lv_demo_widgets\assets\img_clothes.c:4:10: fatal error: lvgl/lvgl.h: No such file or directory
 #include "lvgl/lvgl.h"
          ^~~~~~~~~~~~~
compilation terminated.


```

**Comment by kisvegabor** [comment]
Note that there is not `lv_examples` for v8 as the examples are merged into the main lvgl repo.

Please try with the latest lv_demos and be sure [these changes](https://github.com/lvgl/lv_demos/commit/4e46c451ba3f28164e6cf269e03166919e6d5251) are there.

**Comment by panzerrr** [comment]
> Note that there is not `lv_examples` for v8 as the examples are merged into the main lvgl repo.
> 
> Please try with the latest lv_demos and be sure [these changes](https://github.com/lvgl/lv_demos/commit/4e46c451ba3f28164e6cf269e03166919e6d5251) are there.

ah ok did you mean that i should download lv_demo from github and overwrite my lv_examples library in Arduino? 
I'm looking into the changes.

**Comment by kisvegabor** [comment]
> ah ok did you mean that i should download lv_demo from github and overwrite my lv_examples library in Arduino?

Yes :slightly_smiling_face:

**Comment by mlyons1340** [comment]
Hi @kisvegabor I would like to follow up with this.  I have the latest versions of lvgl and lv_demo installed and I'm running the LVGL_Arduino.ino example in Arduino IDE 1.8.16 on an ESP32.  I am able to run the `lv_demo_benchmark` and `lv_demo_music` without issue.  I would now like to run some of the example code found in the `lvgl/examples` folder.  When I call the function `lv_example_btn_1` as suggested in the demo I get the following:
```
LVGL_Arduino:89:5: error: 'lv_example_btn_1' was not declared in this scope

     lv_example_btn_1();

     ^~~~~~~~~~~~~~~~

C:\Users\mlyon\Dropbox\***\Firmware\LVGL_Arduino\LVGL_Arduino.ino:89:5: note: suggested alternative: 'lv_imgbtn_t'

     lv_example_btn_1();

     ^~~~~~~~~~~~~~~~

     lv_imgbtn_t

Using library lvgl at version 8.1.0-dev in folder: C:\Users\mlyon\Documents\Arduino\libraries\lvgl 

Using library TFT_eSPI at version 2.3.70 in folder: C:\Users\mlyon\Documents\Arduino\libraries\TFT_eSPI 

Using library SPI at version 2.0.0 in folder: C:\Users\mlyon\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\libraries\SPI 

Using library FS at version 2.0.0 in folder: C:\Users\mlyon\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\libraries\FS 

Using library SPIFFS at version 2.0.0 in folder: C:\Users\mlyon\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\libraries\SPIFFS 

Using library lv_demos at version 8.1.0-dev in folder: C:\Users\mlyon\Documents\Arduino\libraries\lv_demos 

exit status 1

'lv_example_btn_1' was not declared in this scope
```
When I copy the code for the example found in `lv_example_btn_1.c` into my Arduino project file I can run the example without error and I get two buttons on my screen as expected.

I have attached my .ino project file for reference.  Any help would be greatly appreciated.

**Comment by mlyons1340** [comment]
I found a work around!  After poking around the code for a while and not finding any reason that `lvgl/examples/lv_examples.h` would not be included I consulted the [Arduino Library Specification](https://arduino.github.io/arduino-cli/0.19/library-specification/#layout-of-folders-and-files) because Arduino does everything weird.  It turns out that only the code in the `src` subfolder will be compiled!  This explains why the code in `lvgl/examples` was not found.  The quick and dirty fix that worked for me was to cut and paste the `examples` folder into the `src` folder and add the line `#include "src/examples/lv_examples.h"` to `lvgl/lvgl.h`.

I would be interested to hear from y'all on what y'all think about this.  I may have just missed something obvious. Either way its a temporary workaround.

**Comment by kisvegabor** [comment]
Ah, that's true. I've updated the [docs](https://github.com/lvgl/lvgl/commit/06962a564fd668eced22b2e9bc19e7732abf94ec).

We were thinking about moving the `examples` into `src` but it's not that logical in general and would be useful only for Arduino.

**Comment by ghost** [comment]
fatal error: lv_demo.h: No such file or directory

**Comment by kisvegabor** [comment]
Have you done [this](https://docs.lvgl.io/master/get-started/platforms/arduino.html#use-the-examples-and-demos)?

**Comment by alamehm** [comment]
Hello @kisvegabor , I have the same problem, I followed the tutroial https://docs.lvgl.io/master/get-started/platforms/arduino.html#use-the-examples-and-demos,  and also tried to modify inside the lvgl.h the includes , adding src in front of them , 
ex. 
#include "src/examples/lv_examples.h"
#include "src/demos/lv_demos.h"
....
But still having the same error in arduino IDE:  'lv_demo_widgets' was not declared in this scope
I am using the original LVGL_arduino sketch.
LVGL version 8.3.6 
################## SOLVED ############### 
check below comment

**Comment by kisvegabor** [comment]
Have you enabled `LV_USE_DEMO_WIDGETS` in `lv_conf.h`?

**Comment by alamehm** [comment]
Thank you @kisvegabor, now it works, it will be convenient if this note will be added to the tutorial.

**Comment by kisvegabor** [comment]
I've updated the ino file here: https://github.com/lvgl/lvgl/commit/beafff266143960d7113eaab2d02bf99d05dbe4e

**Comment by yesnoj** [comment]
Hi @kisvegabor , i'm trying to compile with Arduino IDE 2.1.0 , but it takes ages to compile...probably more than 10 mins.
Is it possible?!?
I've successfully seen the label on screen, my hardware is an ESP32 S3 with an ILI9488 display...but every compile is super slow,
what could be the issue?!

**Comment by kisvegabor** [comment]
I think we can't do much with it on LVGL's side. :slightly_frowning_face: 

Probably Arduino is building on one core, which can be really slow.

**Comment by yesnoj** [comment]
> I think we can't do much with it on LVGL's side. 🙁
> 
> Probably Arduino is building on one core, which can be really slow.

Do you suggest to start learning something new? I can't wait 10 mins (checked with clock) every compile :/

**Comment by alamehm** [comment]
Hello
I suggest you use Platformio on Vscode, with arduino framework, it made a
big difference for me.

**Comment by yesnoj** [comment]
> 

Thanks a lot for your suggestion!
However i've just installed all the stuff on my Macbook Air M1 and it compile in less than 1 min...i don't know if on the Windows pc there is such a protection that slow down to 10 minutes all the process...

Now i need to understand why is suuuuuper laggy the UI...i'm testing the lv_demo_keypad_encoder() to see what offer this library...i really don't need so much stuff...just what is presented in this demo....but is super laggy...maybe somethig i set is wrong in the board?!

**Comment by kisvegabor** [comment]
Regarding the lag, please take look at this: https://docs.lvgl.io/8.3/intro/index.html#how-to-speed-up-my-ui
